using OptiHack.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace OptiHack.UI;

[GenerateTypedNameReferences]
public sealed partial class OptiHackMenu : Window.OptiHackWindow
{
    private readonly IEyeManager _eye = IoCManager.Resolve<IEyeManager>();
    private readonly ILightManager _light = IoCManager.Resolve<ILightManager>();
    private readonly ContainerContentAnalyzerSystem _containerContentAnalyzer = new();
    private readonly KiroshiSystem _hudSystem = new();
    
    
    public OptiHackMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        TitleLabel.Text = "OptiHack UI";
        
        
        
        Overlay.Pressed = false;
        Hud.Pressed = false;
        Fov.Pressed = !_eye.CurrentEye.DrawFov;
        
        Overlay.OnToggled += _ => ToggleOverlay();
        Hud.OnToggled += _ => _hudSystem.ToggleIcons();
        Fov.OnToggled += args => _eye.CurrentEye.DrawFov = !args.Pressed;
        Shadows.OnToggled += args => _light.DrawShadows = !args.Pressed;
        Scan.OnPressed += _ => ScanSlots();
    }

    private void ToggleOverlay()
    {
        var overlaySystem = EntitySystem.Get<OptiHackOverlaySystem>();
        overlaySystem.Enabled ^= true;
    }

    private void ScanSlots()
    {
        var uid = _containerContentAnalyzer.TargetUidParser(Uid.Text);
        var content = _containerContentAnalyzer.ScanAllSlots(uid);
        
        OutputMessage(content);
    }
    private void OutputMessage(List<string> content)
    {
        var formatedMessage = new FormattedMessage();
        
        foreach (var item in content)
        {
            if(item.Contains("{GUN}") || item.Contains("{ANTAG}"))
            {
                formatedMessage.PushColor(Color.Red);
            }
            formatedMessage.AddMarkupPermissive(item);
            formatedMessage.PushNewline();
            formatedMessage.Pop();
            formatedMessage.PushColor(Color.White);
        }
        Info.SetMessage(formatedMessage);
    }
}