using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace OptiHack.UI.Window;

[GenerateTypedNameReferences]
public partial class OptiHackWindow : BaseWindow
{

    public OptiHackWindow()
    {
        RobustXamlLoader.Load(this);
        
        CloseButton.OnPressed += _ => Close();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}